# Generated by Django 4.1.3 on 2022-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField()),
                ('photo', models.FileField(upload_to='teachers/')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('age', models.CharField(max_length=50)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
