# Generated by Django 4.1.3 on 2022-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
