# Generated by Django 4.1.3 on 2022-11-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_text_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.SlugField(max_length=130, null=True),
        ),
    ]
