# Generated by Django 4.1.3 on 2022-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('choice', models.CharField(max_length=50)),
                ('call_time', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
