# Generated by Django 4.1.3 on 2022-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.SlugField(max_length=130, null=True),
        ),
    ]
